#!/bin/bash
export XDG_RUNTIME_DIR="/run/user/1000"
cd "/home/pi/Desktop/polyppi-main"
rm -r "/home/pi/Desktop/polyppi-main/recordings"
rm -r "/home/pi/Desktop/polyppi-main/playback"
rm -r "/home/pi/Desktop/polyppi-main/logs"
mkdir "/home/pi/Desktop/polyppi-main/recordings"
mkdir "/home/pi/Desktop/polyppi-main/playback"
mkdir "/home/pi/Desktop/polyppi-main/logs"
python3 "/home/pi/Desktop/polyppi-main/statemachine.py"
