#!/bin/bash
export XDG_RUNTIME_DIR="/run/user/1000"
cd "/home/marek/Desktop/polyppi"
rm -r "/home/marek/Desktop/polyppi/recordings"
rm -r "/home/marek/Desktop/polyppi/playback"
rm -r "/home/marek/Desktop/polyppi/logs"
mkdir "/home/marek/Desktop/polyppi/recordings"
mkdir "/home/marek/Desktop/polyppi/playback"
mkdir "/home/marek/Desktop/polyppi/logs"
python3 "/home/marek/Desktop/polyppi/statemachine.py"
